name: Coverage

on:
  push:
    branches:
    - main

jobs:
  coverage-time-overlapping:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - name: Collect coverage
      run: |
        flutter pub get
        flutter pub global activate test_coverage
        flutter pub global run test_coverage --exclude "**/js/**"
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        path_to_write_report: ./coverage/codecov_report.txt
